---
fixtures:
  repositories:
    concat: https://github.com/simp/puppetlabs-concat
    compliance_markup: https://github.com/simp/pupmod-simp-compliance_markup
    iptables: https://github.com/simp/pupmod-simp-iptables
    pam: https://github.com/simp/pupmod-simp-pam
    oddjob: https://github.com/simp/pupmod-simp-oddjob
    simplib: https://github.com/simp/pupmod-simp-simplib
    sshkeys_core:
      repo: https://github.com/simp/pupmod-puppetlabs-sshkeys_core.git
      puppet_version: ">= 6.0.0"
    stdlib: https://github.com/simp/puppetlabs-stdlib
    sudo: https://github.com/simp/pupmod-simp-sudo

  symlinks:
    simp_bolt: "#{source_dir}"
