---
fixtures:
  repositories:
    concat:
      # master is beyond 4.1.1, but has breaking changes to
      # how fragments are ordered (MODULES-6625)
      repo: https://github.com/simp/puppetlabs-concat
      ref: 4.1.1
    iptables: https://github.com/simp/pupmod-simp-iptables
    pam: https://github.com/simp/pupmod-simp-pam
    simplib: 
      repo: https://github.com/m-morrone/pupmod-simp-simplib
      branch: SIMP-6366
    sshkeys_core:
      repo: https://github.com/simp/pupmod-puppetlabs-sshkeys_core.git
      puppet_version: ">= 6.0.0"
    stdlib: https://github.com/simp/puppetlabs-stdlib
    sudo: https://github.com/simp/pupmod-simp-sudo

  symlinks:
    simp_bolt: "#{source_dir}"
