---
fixtures:
  repositories:
    iptables: https://github.com/simp/pupmod-simp-iptables
    stdlib: https://github.com/simp/puppetlabs-stdlib
    sudo: https://github.com/simp/pupmod-simp-sudo
    pam: https://github.com/simp/pupmod-simp-pam
    concat:
      # master is beyond 4.1.1, but has breaking changes to
      # how fragments are ordered (MODULES-6625)
      repo: https://github.com/simp/puppetlabs-concat
      ref: 4.1.1
    simplib: 
      repo: https://github.com/m-morrone/pupmod-simp-simplib
      branch: SIMP-6366
  symlinks:
    simp_bolt: "#{source_dir}"
